export default {
  hands: {
    name: "None",
    powerVsFoot: 5,
    powerVsMounted: 5,
    volume: 1,
    weight: 0,
  },
  sword: {
    name: "Sword",
    powerVsFoot: 30,
    powerVsMounted: 20,
    volume: 4,
    weight: 5,
  },
  spear: {
    name: "Spear",
    powerVsFoot: 30,
    powerVsMounted: 30,
    volume: 3,
    weight: 5,
  },
  pike: {
    name: "Pike",
    powerVsFoot: 20,
    powerVsMounted: 40,
    volume: 2,
    weight: 7,
  },
  longbow: {
    name: "Longbow",
    powerVsFoot: 30,
    powerVsMounted: 30,
    volume: 1,
    weight: 3,
  },
  bayonete: {
    name: "Bayonete",
    powerVsFoot: 15,
    powerVsMounted: 15,
    volume: 1,
    weight: 1,
  },
  brownBessSmoothbore: { // Standard revolutionary war rifle
    name: "Brown Bess Smooth Bore",
    powerVsFoot: 60,
    powerVsMounted: 60,
    volume: 3,
    weight: 3,
  },
  confederateSmoothbore: { // Standard union civil war rifle
    name: "Smoothbore Musket",
    powerVsFoot: 60,
    powerVsMounted: 60,
    volume: 4,
    weight: 3,
  },
  springfieldRifledMusket: { // Standard union civil war rifle
    name: "Springfield Rifled Musket",
    powerVsFoot: 70,
    powerVsMounted: 70,
    volume: 4,
    weight: 3,
  },
  cannon24PounderCivilWar: { // Standard civil war cannon
    name: "24 Pounder",
    powerVsFoot: 500,
    powerVsMounted: 500,
    volume: 1,
    weight: 10,
  },
  leeEnfield303: { // Standard ww1 rifle
    name: "Lee Enfield 303",
    powerVsFoot: 75,
    powerVsMounted: 75,
    volume: 5,
    weight: 3,
  }
};
